from .tabwidget import *
from .tools import *
from .ui_avatar import *
from .ui_menu import *
from .ui_mouse import *
from .ui_other import *
from .ui_pm import *
from .ui_summary import *
from .ui_theme import *
from .ui_wallpaper import *
from .ui_welcome import *